"""initial

Revision ID: 88159743e25b
Revises: 
Create Date: 2026-06-21 23:18:48.745675

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '88159743e25b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_technologies_category_id'), 'technologies', ['category_id'], unique=False)
    op.create_table('compatibilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tech_a', sa.Integer(), nullable=False),
    sa.Column('tech_b', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tech_a'], ['technologies.id'], ),
    sa.ForeignKeyConstraint(['tech_b'], ['technologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compatibilities_tech_a'), 'compatibilities', ['tech_a'], unique=False)
    op.create_index(op.f('ix_compatibilities_tech_b'), 'compatibilities', ['tech_b'], unique=False)
    op.create_table('tech_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tech_id', sa.Integer(), nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['attr_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['tech_id'], ['technologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_scores_attr_id'), 'tech_scores', ['attr_id'], unique=False)
    op.create_index(op.f('ix_tech_scores_tech_id'), 'tech_scores', ['tech_id'], unique=False)
    op.create_index('ix_techscores_tech_attr', 'tech_scores', ['tech_id', 'attr_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_techscores_tech_attr', table_name='tech_scores')
    op.drop_index(op.f('ix_tech_scores_tech_id'), table_name='tech_scores')
    op.drop_index(op.f('ix_tech_scores_attr_id'), table_name='tech_scores')
    op.drop_table('tech_scores')
    op.drop_index(op.f('ix_compatibilities_tech_b'), table_name='compatibilities')
    op.drop_index(op.f('ix_compatibilities_tech_a'), table_name='compatibilities')
    op.drop_table('compatibilities')
    op.drop_index(op.f('ix_technologies_category_id'), table_name='technologies')
    op.drop_table('technologies')
    op.drop_table('categories')
    op.drop_table('attributes')
    # ### end Alembic commands ###
